---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currencycalculation
    version: v1
  name: currencycalculation
spec:
  ports:
    -
      name: http
      port: 8100
      targetPort: 8100
  selector:
    app: currencycalculation
    version: v1
  type: NodePort
